apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: bluegreen
spec:
  template:
    spec:
      containers:
        - name: bluegreen
          env:
            - name: COLOR
              value: green 
